package com.tieniilfilo.app.ui.theme

import androidx.compose.ui.graphics.Color

// Light theme — neopastel vibrante
val LightPrimary = Color(0xFFE66A3C)
val LightOnPrimary = Color(0xFFFFFFFF)
val LightPrimaryContainer = Color(0xFFFFD9CC)
val LightOnPrimaryContainer = Color(0xFF3B1A0C)
val LightSecondary = Color(0xFFFF8A5B)
val LightOnSecondary = Color(0xFFFFFFFF)
val LightSecondaryContainer = Color(0xFFFFE0D0)
val LightOnSecondaryContainer = Color(0xFF3B1A0C)
val LightTertiary = Color(0xFF6FCE6F)
val LightOnTertiary = Color(0xFFFFFFFF)
val LightTertiaryContainer = Color(0xFFC8F0C8)
val LightOnTertiaryContainer = Color(0xFF1C3623)
val LightBackground = Color(0xFFFFF8F0)
val LightOnBackground = Color(0xFF2C2418)
val LightSurface = Color(0xFFFFF2E5)
val LightOnSurface = Color(0xFF2C2418)
val LightSurfaceVariant = Color(0xFFFAE5D0)
val LightOnSurfaceVariant = Color(0xFF73685E)
val LightOutline = Color(0xFFA38F80)
val LightError = Color(0xFFBA1A1A)
val LightOnError = Color(0xFFFFFFFF)

// Dark theme
val DarkPrimary = Color(0xFFFF9B6B)
val DarkOnPrimary = Color(0xFF5A2A14)
val DarkPrimaryContainer = Color(0xFF7A3C24)
val DarkOnPrimaryContainer = Color(0xFFFFDAD4)
val DarkSecondary = Color(0xFFFFB8A2)
val DarkOnSecondary = Color(0xFF5A2A14)
val DarkSecondaryContainer = Color(0xFF9D604E)
val DarkOnSecondaryContainer = Color(0xFFFFDAD4)
val DarkTertiary = Color(0xFF9BDD9B)
val DarkOnTertiary = Color(0xFF1C3623)
val DarkTertiaryContainer = Color(0xFF405840)
val DarkOnTertiaryContainer = Color(0xFFC8F0C8)
val DarkBackground = Color(0xFF241612)
val DarkOnBackground = Color(0xFFE9DDD4)
val DarkSurface = Color(0xFF33211A)
val DarkOnSurface = Color(0xFFE9DDD4)
val DarkSurfaceVariant = Color(0xFF4A3C32)
val DarkOnSurfaceVariant = Color(0xFFC9B5A8)
val DarkOutline = Color(0xFF928177)
val DarkError = Color(0xFFFFB4AB)
val DarkOnError = Color(0xFF690005)

// Hero gradient accent tokens (for detail screen headers / home bento)
val HeroAmber = Color(0xFFFFB74D)
val HeroSage = Color(0xFF81C784)
val HeroRose = Color(0xFFF06292)
val HeroCoral = Color(0xFFFF8A65)
