package com.tieniilfilo.app.ui.theme

import androidx.compose.ui.graphics.Color

// Light theme colors — palette più calda e viva
val LightPrimary = Color(0xFF8B5E50)
val LightOnPrimary = Color(0xFFFFFFFF)
val LightPrimaryContainer = Color(0xFFF5D6CC)
val LightOnPrimaryContainer = Color(0xFF3B2721)
val LightSecondary = Color(0xFFD4876A)
val LightOnSecondary = Color(0xFFFFFFFF)
val LightSecondaryContainer = Color(0xFFFCEAE3)
val LightOnSecondaryContainer = Color(0xFF3B2721)
val LightTertiary = Color(0xFF7BA37B)
val LightOnTertiary = Color(0xFFFFFFFF)
val LightTertiaryContainer = Color(0xFFDEE8CF)
val LightOnTertiaryContainer = Color(0xFF1C3623)
val LightBackground = Color(0xFFFFF5EB)
val LightOnBackground = Color(0xFF2C2418)
val LightSurface = Color(0xFFFFF0E0)
val LightOnSurface = Color(0xFF2C2418)
val LightSurfaceVariant = Color(0xFFF5E6D3)
val LightOnSurfaceVariant = Color(0xFF73685E)
val LightOutline = Color(0xFF73685E)
val LightError = Color(0xFFBA1A1A)
val LightOnError = Color(0xFFFFFFFF)

// Dark theme colors
val DarkPrimary = Color(0xFFF5C4B0)
val DarkOnPrimary = Color(0xFF4A2E24)
val DarkPrimaryContainer = Color(0xFF6E473A)
val DarkOnPrimaryContainer = Color(0xFFFFDAD4)
val DarkSecondary = Color(0xFFFFB8A2)
val DarkOnSecondary = Color(0xFF4A2E24)
val DarkSecondaryContainer = Color(0xFF9D604E)
val DarkOnSecondaryContainer = Color(0xFFFFDAD4)
val DarkTertiary = Color(0xFFA9D4A9)
val DarkOnTertiary = Color(0xFF1C3623)
val DarkTertiaryContainer = Color(0xFF405840)
val DarkOnTertiaryContainer = Color(0xFFC5E8C5)
val DarkBackground = Color(0xFF1E1612)
val DarkOnBackground = Color(0xFFE9DDD4)
val DarkSurface = Color(0xFF2C221D)
val DarkOnSurface = Color(0xFFE9DDD4)
val DarkSurfaceVariant = Color(0xFF4A3C32)
val DarkOnSurfaceVariant = Color(0xFFC9B5A8)
val DarkOutline = Color(0xFF928177)
val DarkError = Color(0xFFFFB4AB)
val DarkOnError = Color(0xFF690005)
